# Generated by Django 3.1.5 on 2021-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_rn', models.CharField(max_length=100)),
                ('std_name', models.CharField(max_length=100)),
                ('std_contact', models.CharField(max_length=100)),
                ('std_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
